# Blogroll: Articles from epsi-rns.gitlab.io
ARCHIVES_GITLAB = (
  ('Semantic UI - Overview', '/frontend/2019/10/21/semantic-ui-overview/'),
  ('PostCSS - Loop - Spacing Class', '/frontend/2019/10/11/postcss-loop-spacing-class/'),
  ('Less - Conditional - Color Class', '/frontend/2019/10/04/less-conditional-color-class/'),
  ('Less - Loop - Spacing Class', '/frontend/2019/10/03/less-loop-spacing-class/'),
  ('Haskell - Tax Tariff - Part Four', '/code/2019/09/04/progressive-tax-tariff-04/'),
  ('Haskell - Tax Tariff - Part Three', '/code/2019/09/03/progressive-tax-tariff-03/'),
  ('Haskell - Tax Tariff - Part Two', '/code/2019/09/02/progressive-tax-tariff-02/'),
  ('Haskell - Tax Tariff - Part One', '/code/2019/09/01/progressive-tax-tariff-01/'),
  ('Jekyll - Overview', '/ssg/2019/08/01/jekyll-overview/'),
  ('Eleventy - Overview', '/ssg/2019/07/01/11ty-overview/'),
  ('Sass - Loop - Spacing Class', '/frontend/2019/06/21/sass-loop-spacing-class/'),
  ('Frankenbulma - Overview', '/frontend/2019/06/11/bulma-md-overview/'),
  ('Materialize - Overview', '/frontend/2019/06/01/materialize-overview/'),
  ('Hexo - Summary', '/ssg/2019/05/30/hexo-summary/'),
  ('Netlify - Deploying', '/ssg/2019/05/29/deploy-netlify/'),
  ('Hexo - Meta - SEO', '/ssg/2019/05/28/hexo-meta-seo/'),
  ('Hexo - Content - Syntax Highlighting', '/ssg/2019/05/27/hexo-syntax-highlighting/'),
  ('Hexo - Content - Raw HTML', '/ssg/2019/05/26/hexo-content-html/'),
  ('Hexo - Content - Markdown', '/ssg/2019/05/25/hexo-content-markdown/'),
  ('Hexo - Content - Blog Post', '/ssg/2019/05/24/hexo-content-post/'),
  ('Hexo - Pagination - Filtering Caveat', '/ssg/2019/05/23/hexo-pagination-filtering-caveat/'),
  ('Hexo - Pagination - Handling URL', '/ssg/2019/05/23/hexo-pagination-handling-url/'),
  ('Hexo - Pagination - Screen Reader', '/ssg/2019/05/22/hexo-pagination-screenreader/'),
  ('Hexo - Pagination - Responsive', '/ssg/2019/05/21/hexo-pagination-responsive/'),
  ('Hexo - Pagination - Indicator', '/ssg/2019/05/20/hexo-pagination-indicator/'),
  ('Hexo - Pagination - Logic', '/ssg/2019/05/19/hexo-pagination-logic/'),
  ('Hexo - Pagination - Adjacent', '/ssg/2019/05/19/hexo-pagination-adjacent/'),
  ('Hexo - Pagination - Navigation', '/ssg/2019/05/18/hexo-pagination-navigation/'),
  ('Hexo - Pagination - Number', '/ssg/2019/05/18/hexo-pagination-number/'),
  ('Hexo - Pagination - Simple', '/ssg/2019/05/17/hexo-pagination-simple/'),
  ('Hexo - Pagination - Introduction', '/ssg/2019/05/17/hexo-pagination-intro/'),
  ('Hexo - EJS - Data', '/ssg/2019/05/16/hexo-ejs-data/'),
  ('Hexo - EJS - Widget', '/ssg/2019/05/15/hexo-ejs-widget/'),
  ('Hexo - EJS - Custom Content Type', '/ssg/2019/05/14/hexo-ejs-custom-output/'),
  ('Hexo - EJS - Section List Layout', '/ssg/2019/05/13/hexo-ejs-section-list-layout/'),
  ('Hexo - EJS - Custom Page Layout', '/ssg/2019/05/12/hexo-ejs-custom-page-layout/'),
  ('Hexo - EJS - Custom Page Introduction', '/ssg/2019/05/11/hexo-ejs-custom-page-intro/'),
  ('Hexo - EJS - Section List Introduction', '/ssg/2019/05/10/hexo-ejs-section-list-intro/'),
  ('Hexo - Bulma - SASS Layout', '/ssg/2019/05/08/hexo-bulma-sass-layout/'),
  ('Hexo - Bulma - SASS Introduction', '/ssg/2019/05/07/hexo-bulma-sass-intro/'),
  ('Hexo - Bulma - CSS Layout', '/ssg/2019/05/06/hexo-bulma-css-layout/'),
  ('Hexo - Bulma - CSS Introduction', '/ssg/2019/05/05/hexo-bulma-css-intro/'),
  ('Hexo - Layout', '/ssg/2019/05/04/hexo-layout/'),
  ('Hexo - Minimal', '/ssg/2019/05/03/hexo-minimal/'),
  ('Hexo - Install', '/ssg/2019/05/02/hexo-install/'),
  ('Hexo - Overview', '/ssg/2019/05/01/hexo-overview/'),
  ('Hugo - Conclusion', '/ssg/2019/04/25/hugo-conclusion/'),
  ('Hugo - Blog Post', '/ssg/2019/04/21/hugo-sass-content/'),
  ('Hugo - Pagination', '/ssg/2019/04/19/hugo-bulma-pagination/'),
  ('Hugo - Data', '/ssg/2019/04/15/hugo-data/'),
  ('Hugo - Widget', '/ssg/2019/04/14/hugo-widget/'),
  ('Hugo - Custom Content Type', '/ssg/2019/04/13/hugo-custom-output/'),
  ('Hugo - Archive', '/ssg/2019/04/12/hugo-archive/'),
  ('Hugo - Taxonomy', '/ssg/2019/04/11/hugo-taxonomy/'),
  ('Hugo - Section List', '/ssg/2019/04/10/hugo-section-list/'),
  ('Hugo - Bulma - SASS Layout', '/ssg/2019/04/08/hugo-bulma-sass-layout/'),
  ('Hugo - Bulma - SASS Introduction', '/ssg/2019/04/07/hugo-bulma-sass-intro/'),
  ('Hugo - Bulma - CSS Layout', '/ssg/2019/04/06/hugo-bulma-css-layout/'),
  ('Hugo - Bulma - CSS Introduction', '/ssg/2019/04/05/hugo-bulma-css-intro/'),
  ('Hugo - Layout', '/ssg/2019/04/03/hugo-layout/'),
  ('Hugo - Minimal', '/ssg/2019/04/02/hugo-minimal/'),
  ('Hugo - Overview', '/ssg/2019/04/01/hugo-overview/'),
  ('Bulma SASS - Helpers', '/frontend/2019/03/10/bulma-sass-helpers/'),
  ('Bulma SASS - Post', '/frontend/2019/03/09/bulma-sass-post/'),
  ('Bulma SASS - Widget', '/frontend/2019/03/08/bulma-sass-panels/'),
  ('Bulma SASS - Responsive Layout', '/frontend/2019/03/07/bulma-sass-layout/'),
  ('Bulma SASS - Custom Class', '/frontend/2019/03/06/bulma-sass-custom/'),
  ('Bulma SASS - Inside a Theme', '/frontend/2019/03/05/bulma-sass-theme/'),
  ('Bulma SASS - Introduction', '/frontend/2019/03/04/bulma-sass-intro/'),
  ('Bulma - Navigation Bar', '/frontend/2019/03/03/bulma-navbar/'),
  ('Bulma - Minimal', '/frontend/2019/03/02/bulma-minimal/'),
  ('Bulma - Overview', '/frontend/2019/03/01/bulma-overview/'),
  ('CSS Layout - Fake Table', '/frontend/2019/02/09/css-layout-fake-table/'),
  ('CSS Layout - Float with Calc', '/frontend/2019/02/07/css-layout-calc/'),
  ('CSS Layout - Grid System', '/frontend/2019/02/05/css-layout-grid/'),
  ('CSS Layout - Flex', '/frontend/2019/02/03/css-layout-flex/'),
  ('CSS Layout - Overview', '/frontend/2019/02/01/css-layout-overview/'),
  ('Windows - Chocolatey - Sass', '/frontend/2019/01/23/windows-choco-sass/'),
  ('Windows - Chocolatey - Hugo', '/ssg/2019/01/21/windows-choco-hugo/'),
  ('Sass - Task Runner', '/frontend/2019/01/15/sass-task-runner/'),
  ('Sass - Common Implementation', '/frontend/2019/01/13/sass-common-compiler/'),
  ('Jekyll Pagination - Screenreader', '/ssg/2019/01/08/jekyll-pagination-screenreader/'),
  ('Jekyll Pagination - Responsive', '/ssg/2019/01/07/jekyll-pagination-responsive/'),
  ('Jekyll Pagination - Indicator', '/ssg/2019/01/06/jekyll-pagination-indicator/'),
  ('Jekyll Pagination - Adjacent', '/ssg/2019/01/05/jekyll-pagination-adjacent/'),
  ('Jekyll Pagination - Number', '/ssg/2019/01/04/jekyll-pagination-number/'),
  ('Jekyll Pagination - Simple', '/ssg/2019/01/03/jekyll-pagination-simple/'),
  ('Jekyll Pagination - Summary', '/ssg/2019/01/01/jekyll-pagination-summary/'),
  ('Hugo - Javacript - lunr Search', '/ssg/2018/12/15/hugo-javascript-search/'),
  ('Hugo - Service', '/ssg/2018/12/10/hugo-service/'),
  ('Hugo - Meta - Opengraph SEO', '/ssg/2018/12/07/hugo-meta-opengraph/'),
  ('Hugo - Syntax Highlighting', '/ssg/2018/12/05/hugo-syntax-highlighting/'),
  ('Hugo - Content - Raw HTML', '/ssg/2018/11/26/hugo-html-content/'),
  ('Hugo - Content - Markdown', '/ssg/2018/11/25/hugo-markdown-content/'),
  ('Hugo - Bootstrap - Blog Post', '/ssg/2018/11/24/hugo-bootstrap-content/'),
  ('Hugo - Pagination - Screen Reader', '/ssg/2018/11/22/hugo-pagination-screenreader/'),
  ('Hugo - SASS - Pagination - Responsive', '/ssg/2018/11/21/hugo-pagination-responsive/'),
  ('Hugo - Pagination - Indicator', '/ssg/2018/11/20/hugo-pagination-indicator/'),
  ('Hugo - Pagination - Adjacent', '/ssg/2018/11/19/hugo-pagination-adjacent/'),
  ('Hugo - Pagination - Number', '/ssg/2018/11/18/hugo-pagination-number/'),
  ('Hugo - Pagination - Simple', '/ssg/2018/11/17/hugo-pagination-simple/'),
  ('Hugo - Data', '/ssg/2018/09/15/hugo-data/'),
  ('Hugo - Widget', '/ssg/2018/09/14/hugo-sidebar/'),
  ('Hugo - Custom Content Type', '/ssg/2018/09/13/hugo-custom-output/'),
  ('Hugo - Archive', '/ssg/2018/09/12/hugo-archive/'),
  ('Hugo - Taxonomy', '/ssg/2018/09/11/hugo-taxonomy/'),
  ('Hugo - Section List', '/ssg/2018/09/10/hugo-section-list/'),
  ('Hugo - Bootstrap - SASS Customization', '/ssg/2018/09/08/hugo-bootstrap-sass-custom/'),
  ('Hugo - Bootstrap - SASS', '/ssg/2018/09/07/hugo-bootstrap-sass/'),
  ('Hugo - Bootstrap - Components', '/ssg/2018/09/06/hugo-bootstrap-components/'),
  ('Hugo - Bootstrap - Layout', '/ssg/2018/09/05/hugo-bootstrap-layout/'),
  ('Hugo - Layout', '/ssg/2018/09/03/hugo-layout/'),
  ('Hugo - Minimal', '/ssg/2018/09/02/hugo-minimal/'),
  ('Hugo - Summary', '/ssg/2018/09/01/hugo-summary/'),
  ('Git Pages - Deploying', '/ssg/2018/08/15/git-hosting/'),
  ('Bootstrap - Install Jekyll on RVM', '/frontend/2018/08/10/bootstrap-cli-rvm-bundle/'),
  ('Bootstrap - Offline Template Examples', '/frontend/2018/08/09/bootstrap-cli-offline/'),
  ('Jekyll - Step by Step', '/ssg/2018/02/21/jekyll-basic/'),
  ('Telegram Bot - Manual Page', '/code/2018/01/29/telegram-bot-loop-manual/'),
  ('Telegram Bot - Makefile', '/code/2018/01/28/telegram-bot-loop-makefile/'),
  ('Telegram Bot - BASH Group Tools', '/code/2018/01/26/telegram-bot-loop-bash-04/'),
  ('Telegram Bot - BASH Option Argument', '/code/2018/01/24/telegram-bot-loop-bash-03/'),
  ('Telegram Bot - BASH Script', '/code/2018/01/23/telegram-bot-loop-bash-02/'),
  ('Telegram Bot - BASH CLI', '/code/2018/01/22/telegram-bot-loop-bash-01/'),
  ('Telegram Bot - Getting Token', '/code/2018/01/21/telegram-bot-token/'),
  ('Telegram Bot - Overview', '/code/2018/01/20/telegram-bot-overview/'),
  ('Bootstrap CLI Webtools - Part Three', '/frontend/2018/01/13/bootstrap-cli-part-three/'),
  ('Bootstrap CLI Webtools - Part Two', '/frontend/2018/01/12/bootstrap-cli-part-two/'),
  ('Bootstrap CLI Webtools - Part One', '/frontend/2018/01/11/bootstrap-cli-part-one/'),
  ('Bootstrap CLI Webtools - Summary', '/frontend/2018/01/10/bootstrap-cli-summary/'),
  ('Jekyll Installation on openSUSE', '/ssg/2018/01/06/ekyll-opensuse-install/'),
  ('The LAMP Stack Evolution', '/backend/2017/07/05/lamp-stack-evolution/'),
  ('Examining Bind in Haskell: Do Notation', '/code/2017/05/24/examining-bind-04/'),
  ('Examining Bind in Haskell: Example using Number', '/code/2017/05/23/examining-bind-03/'),
  ('Examining Bind in Haskell: Hello World', '/code/2017/05/22/examining-bind-02/'),
  ('Explaining Monad: References', '/code/2017/05/21/explaining-monad-01/'),
  ('Explaining Monad: Overview', '/code/2017/05/20/explaining-monad-00/'),
  ('Loop in Haskell With Map, Part Three', '/code/2017/05/15/haskell-loop-with-map-03/'),
  ('Loop in Haskell With Map, Part Two', '/code/2017/05/14/haskell-loop-with-map-02/'),
  ('Loop in Haskell With Map, Part One', '/code/2017/05/13/haskell-loop-with-map-01/'),
  ('Loop in Haskell With Map, Overview', '/code/2017/05/12/haskell-loop-with-map-00/'),
  ('Jekyll Directory Structure', '/ssg/2016/12/04/jekyll-directory-structure/'),
  ('Inkscape Logo Creation Part Three', '/design/inkscape/inkscape-logo-03-coloring/'),
  ('Inkscape Logo Creation Part Two', '/design/inkscape/inkscape-logo-02-making-shape-example/'),
  ('Inkscape Logo Creation Part One', '/design/inkscape/inkscape-logo-01-preparing-document/'),
  ('Inkscape: Text Feature', '/design/inkscape/inkscape-text-feature/'),
  ('Inkscape: Flat Wallpaper with Isometric Looks', '/design/inkscape/inkscape-flat-isometric-wallpaper/'),
  ('Jekyll Collapsed Sidemenu Without Javascript', '/ssg/2016/08/13/jekyll-sidemenu-without-javascript/'),
  ('Jekyll Sidemenu Simple Tree', '/ssg/2016/08/12/jekyll-sidemenu-simpletree/'),
  ('Jekyll Responsive Side Menu', '/ssg/2016/08/11/jekyll-responsive-sidemenu/'),
  ('Jekyll Installation on Debian', '/ssg/2016/06/23/jekyll-debian-install/'),
  ('Jekyll Installation on Arch/Manjaro', '/ssg/2016/06/22/jekyll-arch-install/'),
  ('Step by Step Guidance to be a Webcoder', '/frontend/2016/06/14/how-a-webcoder-begin/'),
  ('Elapsed Time, Yet Another Jekyll Liquid Port', '/ssg/2016/06/12/jekyll-liquid-time-elapsed/'),
  ('Create Stripes Using Inkscape to Decorate Blog Post', '/frontend/2016/06/10/stripes-to-decorate-blog-post/'),
  ('Jekyll Post Archives Without Plugin', '/ssg/2016/06/09/jekyll-post-archives-without-plugin/'),
  ('Jekyll Related Posts Without Plugin', '/ssg/2016/05/29/jekyll-related-posts-without-plugin/'),
  ('Jekyll Blog Overview', '/ssg/2016/05/14/jekyll-blog-overview/'),
  ('How Haskell Syntax can Make Your Code Cleaner', '/code/2016/05/14/haskell-dollar-syntax/'),
  ('Inkscape: Anti Corruption Movement', '/design/inkscape/inkscape-anti-corruption-movement/'),
  ('Inkscape: Isometric Infographics', '/design/inkscape/inkscape-isometric-infographics/'),
  ('Inkscape: Another Discussion e-Flyer', '/design/inkscape/inkscape-discussion-flyer/'),
  ('Setup LAMP stack with Manjaro OpenRC', '/backend/2015/10/16/lamp-stack-manjaro-openrc/'),
  ('Inkscape: Object Clip', '/design/inkscape/inkscape-object-clip/'),
  ('Multipurpose Design Based on Stamp Ornament Box', '/design/inkscape/inkscape-stamp-poster-flyer/'),
  ('Inkscape: Vexel Face Tracing', '/design/inkscape/inkscape-vexel-face-tracing/'),
  ('Inkscape: Logo with Stamp Ornament', '/design/inkscape/inkscape-stamp-logo/'),
  ('Inkscape: Event Invitation Stock Image', '/design/inkscape/inkscape-invitation-stock/'),
  ('Inkscape: Event Banner Collection', '/design/inkscape/inkscape-event-banners/'),
  ('Inkscape: Event Schedule Announcement', '/design/inkscape/inkscape-event-schedule/'),
  ('Inkscape: Non Standard Alumni Logo', '/design/inkscape/inkscape-non-standard-makara/'),
)
