# Pelican Data: archives_github.py

# Blogroll: Articles from epsi-rns.github.io

ARCHIVES_GITHUB = (
  ("Awesome WM - Presentation - Statusbar", '/desktop/2019/12/03/awesome-presentation-statusbar.html'),
  ("Awesome WM - Presentation - Theme", '/desktop/2019/12/02/awesome-presentation-theme.html'),
  ("Awesome WM - Presentation - Modularized", '/desktop/2019/12/01/awesome-presentation-modularized.html'),
  ("Awesome WM - Statusbar - Arrow Style", '/desktop/2019/11/28/awesome-statusbar-arrow.html'),
  ("Awesome WM - Statusbar - Lain Library", '/desktop/2019/11/27/awesome-statusbar-lain.html'),
  ("Awesome WM - Statusbar - Vicious Library", '/desktop/2019/11/26/awesome-statusbar-vicious.html'),
  ("Awesome WM - Statusbar - Stacked", '/desktop/2019/11/25/awesome-statusbar-stacked.html'),
  ("Awesome WM - Statusbar - Refactoring Default", '/desktop/2019/11/24/awesome-statusbar-default.html'),
  ("Awesome WM - Theme - Statusbar Icons", '/desktop/2019/10/23/awesome-theme-icons.html'),
  ("Awesome WM - Theme - Layout Icons", '/desktop/2019/10/22/awesome-theme-layout.html'),
  ("Awesome WM - Theme - Titlebar", '/desktop/2019/10/21/awesome-theme-titlebar.html'),
  ("Awesome WM - Theme - Main", '/desktop/2019/10/20/awesome-theme-main.html'),
  ("Awesome WM - Statusbar Modules", '/desktop/2019/06/19/awesome-modularized-statusbar.html'),
  ("Awesome WM - Binding Modules", '/desktop/2019/06/18/awesome-modularized-binding.html'),
  ("Awesome WM - Main Modules", '/desktop/2019/06/17/awesome-modularized-main.html'),
  ("Awesome WM - Modularized Structure", '/desktop/2019/06/16/awesome-modularized-structure.html'),
  ("Awesome WM - Overview", '/desktop/2019/06/15/awesome-overview.html'),
  ("Conky with Lua Scripting", '/desktop/2019/06/11/modularized-conky.html'),
  ("GhostBSD - Ports", '/system/2019/04/02/ghostbsd-ports.html'),
  ("GhostBSD - Migration from Linux", '/system/2019/03/30/ghostbsd-migration.html'),
  ("GhostBSD - Driver", '/system/2019/03/25/ghostbsd-driver.html'),
  ("GhostBSD - Multiboot", '/system/2019/03/20/ghostbsd-multiboot.html'),
  ("Windows - Setting up CLI Environment", '/system/2019/01/21/windows-cli-environment.html'),
  ("Gentoo - Selective Emerge with Equery", '/system/2019/01/01/gentoo-selective-emerge.html'),
  ("Linux - Terminal Customization", '/desktop/2018/08/07/terminal-ricing.html'),
  ("Openbox Install - obmenu-generator", '/desktop/2018/07/18/openbox-install.html'),
  ("Openbox Install - oblogout", '/desktop/2018/07/17/openbox-install.html'),
  ("Openbox Install - Common Utility", '/desktop/2018/07/16/openbox-install.html'),
  ("Openbox Install - Basic", '/desktop/2018/07/15/openbox-install.html'),
  ("Audio Command Line, a must have Knowledge", '/system/2018/06/22/audio-command-line.html'),
  ("Distribution - Slackware Plasma 5", '/system/2018/05/30/distro-slackware-plasma5.html'),
  ("Linux Network - Samba", '/system/2018/05/25/linux-samba.html'),
  ("Linux Multiboot - chroot", '/system/2018/05/23/linux-multiboot.html'),
  ("Linux Multiboot - /etc/fstab", '/system/2018/05/22/linux-multiboot.html'),
  ("Linux Multiboot - Partition Schema", '/system/2018/05/21/linux-multiboot.html'),
  ("Tint2 - Panel Items", '/desktop/2018/05/17/tint2-config.html'),
  ("Tint2 - More Backgrounds", '/desktop/2018/05/16/tint2-config.html'),
  ("Tint2 - Simple Taskbar", '/desktop/2018/05/15/tint2-config.html'),
  ("Openbox Utility - Exit", '/desktop/2018/05/12/openbox-exit.html'),
  ("Openbox Menu - Exit", '/desktop/2018/05/11/openbox-config.html'),
  ("Openbox Menu - OB Menu Generator", '/desktop/2018/05/10/openbox-config.html'),
  ("Openbox Menu - XDG Applications", '/desktop/2018/05/09/openbox-config.html'),
  ("Openbox Menu - Dynamic", '/desktop/2018/05/08/openbox-config.html'),
  ("Openbox Menu - Static", '/desktop/2018/05/07/openbox-config.html'),
  ("Openbox Config - Rules", '/desktop/2018/05/05/openbox-config.html'),
  ("Openbox Config - Key and Mouse Binding", '/desktop/2018/05/04/openbox-config.html'),
  ("Openbox Config - General rc.xml", '/desktop/2018/05/03/openbox-config.html'),
  ("Openbox Config - Overview", '/desktop/2018/05/01/openbox-config.html'),
  ("Openbox Theme - Special Trick", '/desktop/2018/04/18/openbox-theme.html'),
  ("Openbox Theme - Common Config Trick", '/desktop/2018/04/17/openbox-theme.html'),
  ("Openbox Theme - Common Inkscape Trick", '/desktop/2018/04/16/openbox-theme.html'),
  ("Openbox Theme - Overview", '/desktop/2018/04/15/openbox-theme.html'),
  ("Fluxbox Theme - Style Part", '/desktop/2018/04/07/fluxbox-style.html'),
  ("Fluxbox Theme - Inkscape Part", '/desktop/2018/04/06/fluxbox-style.html'),
  ("Fluxbox Config - Menu", '/desktop/2018/04/04/fluxbox-config.html'),
  ("Fluxbox Config - General", '/desktop/2018/04/03/fluxbox-config.html'),
  ("Fluxbox Overview", '/desktop/2018/04/01/fluxbox-overview.html'),
  ("XFWM4 Theme - Part Five", '/desktop/2018/03/25/xfwm4-theme.html'),
  ("XFWM4 Theme - Part Four", '/desktop/2018/03/24/xfwm4-theme.html'),
  ("XFWM4 Theme - Part Three", '/desktop/2018/03/23/xfwm4-theme.html'),
  ("XFWM4 Theme - Part Two", '/desktop/2018/03/22/xfwm4-theme.html'),
  ("XFWM4 Theme - Part One", '/desktop/2018/03/21/xfwm4-theme.html'),
  ("XFWM4 Theme - Overview", '/desktop/2018/03/20/xfwm4-theme.html'),
  ("Linux - Installing Font", '/desktop/2018/02/04/installing-font.html'),
  ("dbus in Window Manager", '/system/2018/01/18/dbus-window-manager.html'),
  ("Distribution - Slackware Post Install Log", '/system/2018/01/17/distro-slackware-post-install.html'),
  ("Using Git for Working Between Computer", '/opensource/2018/01/15/using-git.html'),
  ("Using Cloud for Daily Activity", '/opensource/2018/01/09/using-cloud.html'),
  ("File System - Trapped in Snapper Rollback", '/system/2018/01/07/btrfs-snapper.html'),
  ("openSUSE Tumbleweed Tiling Experience", '/desktop/2018/01/02/opensuse-tiling.html'),
  ("Parsing BASH command in ZSH", '/code/2017/12/30/parse-bash-in-zsh.html'),
  ("Iterate Oh My BASH Theme", '/desktop/2017/12/26/oh-my-shell-theme.html'),
  ("Docker - Package Management Summary", '/system/2017/08/31/docker-package-summary.html'),
  ("Docker - LFS Build", '/system/2017/08/30/docker-lfs-build.html'),
  ("Docker - Arch ALPM - Part Four", '/system/2017/08/30/docker-arch-alpm.html'),
  ("Docker - Arch ALPM - Part Three", '/system/2017/08/29/docker-arch-alpm.html'),
  ("Docker - Arch ALPM - Part Two", '/system/2017/08/28/docker-arch-alpm.html'),
  ("Docker - Arch ALPM - Part One", '/system/2017/08/27/docker-arch-alpm.html'),
  ("Docker - Debian APT - Part Four", '/system/2017/08/27/docker-debian-apt.html'),
  ("Docker - Debian APT - Part Three", '/system/2017/08/26/docker-debian-apt.html'),
  ("Docker - Debian APT - Part Two", '/system/2017/08/25/docker-debian-apt.html'),
  ("Docker - Debian APT - Part One", '/system/2017/08/24/docker-debian-apt.html'),
  ("Docker - Slackware Package - Part Three", '/system/2017/08/23/docker-slackware-package.html'),
  ("Docker - Slackware Package - Part Two", '/system/2017/08/22/docker-slackware-package.html'),
  ("Docker - Slackware Package - Part One", '/system/2017/08/21/docker-slackware-package.html'),
  ("Docker - Fedora DNF - Part Four", '/system/2017/08/21/docker-fedora-dnf.html'),
  ("Docker - Fedora DNF - Part Three", '/system/2017/08/20/docker-fedora-dnf.html'),
  ("Docker - Fedora DNF - Part Two", '/system/2017/08/19/docker-fedora-dnf.html'),
  ("Docker - Fedora DNF - Part One", '/system/2017/08/18/docker-fedora-dnf.html'),
  ("Docker - openSUSE Zypper - Part Four", '/system/2017/08/18/docker-opensuse-zypper.html'),
  ("Docker - openSUSE Zypper - Part Three", '/system/2017/08/17/docker-opensuse-zypper.html'),
  ("Docker - openSUSE Zypper - Part Two", '/system/2017/08/16/docker-opensuse-zypper.html'),
  ("Docker - openSUSE Zypper - Part One", '/system/2017/08/15/docker-opensuse-zypper.html'),
  ("Docker - Void XBPS - Part Two", '/system/2017/08/14/docker-void-xbps.html'),
  ("Docker - Void XBPS - Part One", '/system/2017/08/13/docker-void-xbps.html'),
  ("Docker - Gentoo Portage - Part Three", '/system/2017/08/13/docker-gentoo-portage.html'),
  ("Docker - Gentoo Portage - Part Two", '/system/2017/08/12/docker-gentoo-portage.html'),
  ("Docker - Gentoo Portage - Part One", '/system/2017/08/11/docker-gentoo-portage.html'),
  ("Docker - Crux Ports", '/system/2017/08/10/docker-crux-ports.html'),
  ("Distribution - Debian to Devuan Migration", '/system/2017/08/08/distro-debian-devuan-migration.html'),
  ("Distribution - Manjaro OpenRC to Artix Migration", '/system/2017/08/07/distro-manjaro-artix-migration.html'),
  ("Distribution - Mageia 6 Upgrade", '/system/2017/08/06/distro-mageia6-upgrade.html'),
  ("File System - GRUB2 support for BTRFS", '/system/2017/08/05/grub2-btrfs-support.html'),
  ("Distribution - openSUSE Tumbleweed First Time Install", '/system/2017/08/03/distro-opensuse-install.html'),
  ("Distribution - Fedora First Time Install", '/system/2017/08/02/distro-fedora-install.html'),
  ("Distribution - Manjaro OpenRC Issues", '/system/2017/08/01/distro-manjaro-openrc.html'),
  ("HerbstluftWM in Seven Languages Summary", '/desktop/2017/06/30/herbstlustwm-summary.html'),
  ("HerbstluftWM Idle Event in Haskell", '/desktop/2017/06/18/herbstlustwm-event-idle-haskell.html'),
  ("HerbstluftWM Idle Event in Lua", '/desktop/2017/06/17/herbstlustwm-event-idle-lua.html'),
  ("HerbstluftWM Idle Event in PHP", '/desktop/2017/06/16/herbstlustwm-event-idle-php.html'),
  ("HerbstluftWM Idle Event in Ruby", '/desktop/2017/06/15/herbstlustwm-event-idle-ruby.html'),
  ("HerbstluftWM Idle Event in Python", '/desktop/2017/06/14/herbstlustwm-event-idle-python.html'),
  ("HerbstluftWM Idle Event in Perl", '/desktop/2017/06/13/herbstlustwm-event-idle-perl.html'),
  ("HerbstluftWM Idle Event in BASH", '/desktop/2017/06/12/herbstlustwm-event-idle-bash.html'),
  ("HerbstluftWM Idle Event Overview", '/desktop/2017/06/11/herbstlustwm-event-idle-overview.html'),
  ("HerbstluftWM Tag Status Global Notes", '/desktop/2017/06/09/herbstlustwm-tag-status-global.html'),
  ("HerbstluftWM Tag Status in Haskell", '/desktop/2017/06/08/herbstlustwm-tag-status-haskell.html'),
  ("HerbstluftWM Tag Status in Lua", '/desktop/2017/06/07/herbstlustwm-tag-status-lua.html'),
  ("HerbstluftWM Tag Status in PHP", '/desktop/2017/06/06/herbstlustwm-tag-status-php.html'),
  ("HerbstluftWM Tag Status in Ruby", '/desktop/2017/06/05/herbstlustwm-tag-status-ruby.html'),
  ("HerbstluftWM Tag Status in Python", '/desktop/2017/06/04/herbstlustwm-tag-status-python.html'),
  ("HerbstluftWM Tag Status in Perl", '/desktop/2017/06/03/herbstlustwm-tag-status-perl.html'),
  ("HerbstluftWM Tag Status in BASH", '/desktop/2017/06/02/herbstlustwm-tag-status-bash.html'),
  ("HerbstluftWM Tag Status Overview", '/desktop/2017/06/01/herbstlustwm-tag-status-overview.html'),
  ("Modularized HerbstluftWM in Haskell", '/desktop/2017/05/08/herbstlustwm-modularized-haskell.html'),
  ("Modularized HerbstluftWM in Lua", '/desktop/2017/05/07/herbstlustwm-modularized-lua.html'),
  ("Modularized HerbstluftWM in PHP", '/desktop/2017/05/06/herbstlustwm-modularized-php.html'),
  ("Modularized HerbstluftWM in Ruby", '/desktop/2017/05/05/herbstlustwm-modularized-ruby.html'),
  ("Modularized HerbstluftWM in Python", '/desktop/2017/05/04/herbstlustwm-modularized-python.html'),
  ("Modularized HerbstluftWM in Perl", '/desktop/2017/05/03/herbstlustwm-modularized-perl.html'),
  ("Modularized HerbstluftWM in BASH", '/desktop/2017/05/02/herbstlustwm-modularized-bash.html'),
  ("Modularized HerbstluftWM Overview", '/desktop/2017/05/01/herbstlustwm-modularized-overview.html'),
  ("Piping and Forking Overview", '/code/2017/04/23/overview-pipe-and-fork.html'),
  ("Debugging Conky", '/desktop/2017/04/22/debugging-conky.html'),
  ("Piping and Forking in Haskell", '/code/2017/04/21/haskell-pipe-and-fork.html'),
  ("Piping and Forking in Lua", '/code/2017/04/20/lua-pipe-and-fork.html'),
  ("Piping and Forking in PHP", '/code/2017/04/19/php-pipe-and-fork.html'),
  ("Piping and Forking in Ruby", '/code/2017/04/18/ruby-pipe-and-fork.html'),
  ("Piping and Forking in Python", '/code/2017/04/17/python-pipe-and-fork.html'),
  ("Piping and Forking in Perl", '/code/2017/04/16/perl-pipe-and-fork.html'),
  ("Piping and Forking in BASH", '/code/2017/04/15/bash-pipe-and-fork.html'),
  ("Standalone Lemonbar Using Conky", '/desktop/2017/04/14/standalone-lemonbar-conky.html'),
  ("Getting XLFD Font", '/desktop/2017/04/13/getting-xlfd-font.html'),
  ("Standalone CLI System Monitoring Using Conky", '/desktop/2017/04/12/standalone-cli-conky.html'),
  ("Standalone Dzen2 Statusbar Using Conky", '/desktop/2017/04/11/standalone-dzen2-conky.html'),
  ("Standalone Statusbar Overview", '/desktop/2017/04/10/standalone-overview.html'),
  ("Create XBM for your Dzen2", '/desktop/2017/04/08/create-xbm-for-dzen2.html'),
  ("Standalone Dzen2 Statusbar Using BASH", '/desktop/2017/04/01/standalone-dzen2-bash.html'),
  ("Manjaro Logo on i3WM on Material Wallpaper", '/desktop/2016/11/19/manjaro-logo.html'),
  ("Install Termite", '/desktop/2016/09/19/termite-install.html'),
  ("Install i3 WM in Arch Linux based Distribution", '/desktop/2016/08/03/i3-install-arch.html'),
  ("Install i3 WM in Debian", '/desktop/2016/08/02/i3-install-debian.html'),
  ("Modularized Conky Configuration for i3status", '/desktop/2016/08/01/modularized-i3status-conky-lua-json.html'),
  ("Preparing Modularized Awesome WM Configuration", '/desktop/2016/07/13/modularized-awesome-preparing.html'),
  ("Modularized Awesome WM Configuration Structure", '/desktop/2016/07/06/modularized-awesome-structure.html'),
  ("Compile .deb Source with apt-src", '/system/2016/07/01/apt-compile-source.html'),
  ("Install Awesome WM in Debian", '/desktop/2016/06/30/awesome-install-debian.html'),
  ("Install Awesome WM in Arch Linux based Distribution", '/desktop/2016/06/29/awesome-install-arch.html'),
  ("Install Yaourt, the AUR Helper", '/system/2016/06/21/install-yaourt.html'),
  ("Using Git for Daily Repo Updating", '/opensource/2016/06/19/using-git.html'),
  ("Analyze Services in Linux Boot Process", '/system/2016/06/16/analyze-boot-services.html'),
  ("Create Your Own Monitoring Script", '/code/2016/06/15/monitoring-script.html'),
  ("The Difference Between DE, Shell, WM and Compositor", '/desktop/2016/06/13/de-wm-shell-difference.html'),
  ("Meet Our Friend, Regular Expression", '/code/2016/06/03/regular-expression.html'),
  ("What to Do, When the System Stuck, on Boot", '/system/2016/05/19/stuck-on-boot.html'),
  ("Midnight Commander Tweaking, can Help People Better", '/desktop/2016/05/19/midnight-commander-tweaking.html'),
  ("Becoming a Geek, a Weird Story About Nerd", '/opensource/2016/05/18/becoming-geek.html'),
  ("XMonad with Conkyless Dzen, Total Control of Theme", '/desktop/2016/05/11/xmonad-with-conkyless-dzen.html'),
  ("Introducing FatRat and Cantata", '/opensource/2016/04/21/introducing-fatrat-cantata.html'),
  ("Channels Worth Following", '/opensource/2016/04/15/channels-worth-following.html'),
  ("Two Languages of The Future", '/opensource/2016/03/29/two-languages-of-the-future.html'),
  ("Modularized XMonad Config", '/desktop/2016/03/26/modularized-xmonad-config.html'),
  ("Customizing Shell Prompt with Powerline", '/desktop/2016/03/21/powerline-customizing.html'),
  ("Console Pixel Art, a Collection of Scripts", '/desktop/2016/03/20/console-pixel-art.html'),
  ("Refactoring Awesome WM's Lua Configuration Script", '/desktop/2016/03/19/refactoring-awesome-lua-configuration.html'),
  ("Learning Stages Guidance, from Beginner to Enthusiast", '/opensource/2016/03/17/learning-stages.html'),
  ("Running Guest OS via Docker on top of Debian for the first time", '/system/2016/03/09/docker-demonstration-debian.html'),
  ("Docker Demonstration (Manjaro), Running Multiple Guest OS", '/system/2016/03/03/docker-demonstration-manjaro.html'),
  ("Learn Different Package Management Using LXC", '/system/2016/02/28/lxc-demonstration.html'),
  ("Update Arch Linux without Unnecessary Bloated Package", '/system/2016/02/08/pacman-ignorepkg.html'),
  ("Control Your Package with APT Pinning", '/system/2015/03/17/apt-pinning.html'),
  ("Minimalist XFCE4 with Limited Tiling Support", '/desktop/2015/02/13/xfce4-minimalis-tiling.html'),
  ("Selectively Install BlackArch Tools", '/system/2014/12/27/selectively-install-blackarch-tools.html'),
  ("Unbundling AUR Helper Process", '/system/2014/12/26/unbundling-aur-helper-process.html'),
  ("XMonad Menu Bar", '/desktop/2014/12/15/xmonad-menu-bar.html'),
  ("XMonad Tiling Window Manager", '/desktop/2014/12/12/xmonad-tiling-window-manager.html'),
  ("i3 Window manager with i3 Bar", '/desktop/2014/12/06/i3-i3bar.html'),
  ("Awesome WM, Tiling WM for beginner", '/desktop/2014/11/30/awesome.html'),
  ("Init Civil War, The systemd Controversy", '/system/2014/11/28/init-civil-wars.html'),
  ("Fluxbox Stacking Window Manager", '/desktop/2014/11/08/fluxbox-with-glowing-wallpaper.html'),
  ("Standalone Openbox WM with Tint2 Panel", '/desktop/2014/11/02/openbox-standalone.html'),
  ("LXQT with Windowish Looks, No Kidding", '/desktop/2014/10/19/lxqt-windowish-looks.html'),
  ("Selfieshoot of Hilarious XFCE4 Customization", '/desktop/2014/05/14/xfce4-hilarious-selfieshoot.html'),
  ("My Mageia Experiment", '/system/2014/05/09/mageia-experiment.html'),
  ("How to Install BlackArch as Repository", '/system/2014/04/27/install-blackarch-as-repository.html'),
  ("Is it a Gnome Shell Customization, or Am I just got bored ?", '/desktop/2014/04/22/gnome-shell-a-very-common.html'),
  ("Arch Linux - Install/ Post Install Log", '/system/2014/04/02/arch-install-log.html'),
  ("Wireless Command Line, a must have Knowledge", '/system/2014/03/13/wireless-command-line.html'),
  ("Linux Multiboot, Setting up Partitions", '/system/2014/03/13/linux-multiboot.html'),
  ("Facebook Groups, Resources for Linux Enthusiast", '/opensource/2014/03/12/facebook-linux-groups.html'),
  ("Gtk3 Adoption Rate in Debian.", '/system/2014/02/22/gtk3-adoption-rate.html'),
  ("Debian Wheezy - Post Install Log", '/system/2014/01/02/debian-post-install-log.html'),
)
