# Blogroll: Helper for friends widget
FRIENDS = ( ('BanditHijo (R)-Chive', 'http://bandithijo.com/'),
            ('Sira Argia (Aflasio)', 'https://aflasio.art/'),
            ('Michael Dion', 'https://www.digimoclub.com'),
            ('Rania Amina', 'https://raniaamina.id/'),
            ("Nanda 'Yunee' Okitavera", 'https://okitavera.me/'),
            ('Adhi Pambudi', 'https://addy-dclxvi.github.io/'),
            ('Yunindyo Prabowo @ gitlab.io', 'http://ypraw.gitlab.io'),
            ('Habib Mustofa', 'https://mustofa.id/'),
            ('Muktazam Hasbi', 'https://muktazam.me'),
            ('Doddy Rizal Novianto', 'https://drzaln.github.io/'),
            ('Arivle', 'http://arivle.github.io'),
            ('epsi @ github.io (desktop)', 'http://epsi-rns.github.io/'),
            ('epsi @ gitlab.io (webdev)', 'http://epsi-rns.github.io/'),
            ('A Sky', 'https://asky-el.gitlab.io'),
            ('Karen', 'http://maidgirl21.github.io'),  
            ('Muhammad Nur Fuad', 'https://illvart.com/'),
            ('Hadi Hidayat Hammurabi', 'http://hadihammurabi.com/'),
            ('Virdio Sam', 'http://diosamuel.netlify.com'),
            ('Sri Aspari', 'https://siarie.me/'),
            ('Teknik Nih (search engine)', 'http://webkartu.com/'),
            ('GIMPScape ID', 'https://gimpscape.org/'),)
