# https://jimkubicek.com/setting-up-github-actions-for-deploying-pelican.html

name: Pelican Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout to master
      uses: actions/checkout@v2
    - name: Set up Python 3.5
      uses: actions/setup-python@v1
      with:
        python-version: 3.5
    - name: Setup the SSH key
      env:
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      run: |
        mkdir $HOME/.ssh
        echo "$PRIVATE_KEY" > $HOME/.ssh/id_rsa
        chmod 600 $HOME/.ssh/id_rsa
        ssh-keyscan -t rsa github.com >> $HOME/.ssh/known_hosts
    - name: Prepare Git Initialization
      run: |
        git config user.email "someone@somewhere"
        git config user.name "someone""
        git remote -v
        echo "[Checking origin/gh-pages]"
        git branch -a -l | grep gh-pages | wc -l
        git branch -a -l | cat
        if [ $(git branch -a -l | grep gh-pages | wc -l) -eq "0" ]; then
          echo "[Create gh-pages for the first time]"
          git checkout -b gh-pages
          git commit --allow-empty -m "Create gh-pages for the first time"
          git push --set-upstream origin gh-pages
          git checkout master
        fi
    - name: Upgrade PIP and Configure Dependencies
      run: |
        python3 -m venv venv
        . venv/bin/activate
        pip install --user --upgrade pip
        pip install -r requirements.txt
    - name: Generate Pelican Static Files
      run: |
        . venv/bin/activate
        make html
    - name: Precheck Output 
      run: |
        pwd
        source=$(pwd)
        git worktree add -B gh-pages ~/public origin/gh-pages
        git worktree list
        cd ~/public
        ls -lah
        find . -maxdepth 1 ! -name '.git' -exec rm -rf {} \;
        mv ${myplace}/output/* .
        touch .nojekyll
        ls -lah
    - name: Deploy Release to GitHub
      run: |
        . venv/bin/activate
        make publish
